#!/usr/bin/env python3
import argparse
import json
import os
import statistics
import collections


def main():
    parser = argparse.ArgumentParser()
    parser.parse_args()
    population = collections.defaultdict(list)
    props = ('brightness', 'max_brightness', 'type')
    stat_fns = ("mean", "median", "median_low", "median_high",
                "median_grouped", "mode", "pstdev", "pvariance", "stdev",
                "variance",)
    for item in os.listdir('submissions'):
        if not item.endswith('.json'):
            continue
        filename = os.path.join('submissions', item)
        with open(filename, 'rt', encoding='UTF-8') as stream:
            data = json.load(stream)
        try:
            bl_id_list = data['backlight']
        except KeyError:
            continue
        for bl_id in bl_id_list:
            for prop in props:
                try:
                    value = data['backlight'][bl_id][prop]
                except KeyError:
                    continue
                else:
                    population[prop].append(value)
        population['num-devices'].append(len(bl_id_list))

    for prop in population.keys():
        print("[{}]".format(prop))
        print("population size", len(population[prop]))
        print("population: ", population[prop])
        for fn in stat_fns:
            try:
                stat = getattr(statistics, fn)(population[prop])
            except TypeError:
                pass
            except statistics.StatisticsError as exc:
                print("{:15} {}".format(fn, exc))
            else:
                print("{:15} {}".format(fn, stat))


if __name__ == '__main__':
    main()
