#!/bin/sh
# This file is part of Lantern.
#
# Copyright 2015 Canonical Ltd.
# Written by:
#   Zygmunt Krynicki <zygmunt.krynicki@canonical.com>
#
# Lantern is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License version 3,
# as published by the Free Software Foundation.
#
# Lantern is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Lantern.  If not, see <http://www.gnu.org/licenses/>.

# Basic backlight data collection script for Lantern

set -x
id=$(cat /proc/sys/kernel/random/uuid)
dest=$(mktemp -d --suffix=-lantern)
lspci > "$dest/lspci"
lsmod > "$dest/lsmod"
uname -a > "$dest/uname"
if [ -e /etc/os-release ]; then
    cp /etc/os-release "$dest/"
fi
SCB=/sys/class/backlight
if [ -e $SCB ]; then
    mkdir "$dest/backlight"
    for device in $(ls $SCB); do
        device_dest="$dest/backlight/$device"
        mkdir "$device_dest"
        cp "$SCB/$device/max_brightness" "$device_dest/"
        cp "$SCB/$device/actual_brightness" "$device_dest/"
        cp "$SCB/$device/brightness" "$device_dest/"
        cp "$SCB/$device/type" "$device_dest/"
    done
fi
tar -Jcf "lantern-submission-$id.tar.xz" -C "$dest" .
rm -rf "$dest"
echo -- "$id"
